# Generated by Django 4.2.13 on 2024-07-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=10)),
                ('activity_level', models.CharField(choices=[('軽度', '軽度'), ('中程度', '中程度'), ('高度', '高度')], max_length=10)),
                ('goal', models.CharField(choices=[('減量', '減量'), ('維持', '維持'), ('増量', '増量')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('朝食', '朝食'), ('昼食', '昼食'), ('夕食', '夕食'), ('間食', '間食')], max_length=10)),
                ('food_items', models.TextField()),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.userprofile')),
            ],
        ),
    ]
